variables:
  DOCKER_DRIVER: overlay2

  HELM_VERSION: 3.1.2
  KUBECTL_VERSION: 1.18.4
  GLIBC_VERSION: 2.31-r0

  BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"

stages:
  - build
#  - test
  - release

include:
  - local: .gitlab/ci/build.gitlab-ci.yml
#  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/release.gitlab-ci.yml
